apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: homelab-dns
data:
  Corefile: |
    .:53 {
      hosts {
        192.168.0.10 web.home.arpa
        fallthrough
      }
      forward . 192.168.0.1
      log
      errors 
    }
