# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Look inside the runner
        run: |
          echo "=== Waar ben ik? ==="
          pwd
          echo "=== Wat staat hier? ==="
          ls -la    
          echo "=== Welke branch/commit heb ik? ==="
          git branch --show-current
          git rev-parse --short HEAD    
          git status
          git log --oneline -3 
      - name: Check for kubectl
        run: which kubectl
      - name: Validate deployment
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -strict kubernetes/apps/web/"    

